name: Build and Deploy ASP.NET Core App to Azure Web App - UICrafter

on:
  push:
    branches:
      - main
      - GitHub-Actions-Android
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore NuGet packages
        run: dotnet restore src/UICrafter/UICrafter.csproj

      - name: Build with dotnet
        run: dotnet build src/UICrafter/UICrafter.csproj --configuration Release --no-restore

      - name: Publish the app
        run: dotnet publish src/UICrafter/UICrafter.csproj --configuration Release --no-build --output ./published_app

      - name: Upload Artifact for Deployment
        uses: actions/upload-artifact@v4
        with:
          name: published_app
          path: ./published_app

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
    permissions:
      id-token: write

    steps:
      - name: Download Artifact from Build Job
        uses: actions/download-artifact@v4
        with:
          name: published_app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'UICrafter'  # Replace with your actual Web App name
          package: ./published_app
